"""Views, one for each Insta485 page."""
from insta485.views.index import show_index
from insta485.views.uploads import get_upload
from insta485.views.user import show_user
from insta485.views.followers import show_followers
from insta485.views.posts import show_posts
from insta485.views.comments import update_comments
from insta485.views.likes import update_likes
from insta485.views.accounts import show_login
from insta485.views.accounts import show_create
from insta485.views.accounts import show_delete
from insta485.views.accounts import show_edit
from insta485.views.accounts import show_password
from insta485.views.accounts import show_auth
from insta485.views.accounts import get_accounts
from insta485.views.accounts import get_logout
from insta485.views.explore import explore_page
from insta485.views.following import update_following
from insta485.views.posts import update_posts
from insta485.views.user_following import show_following
